//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N30MvcCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int CID { get; set; }
        public string CName { get; set; }
        public int CCount { get; set; }
        public string CImg { get; set; }
        public bool CIsDel { get; set; }
        public System.DateTime CAddTime { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
