//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace N30MvcCrud.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Student
    {
        public int Id { get; set; }
        [Required]  // 不能为空, 必须为数值类型
        [Range(1, 20)]  // [最小值, 最大值]
        public Nullable<int> CId { get; set; }
        [DisplayName("姓名")]       // 显示 @Html.LableFor(s => s.Name)
        [StringLength(10, ErrorMessage = "字符长度不能长过10")]   // 验证 @Html.ValidationMessageFor(s => s.Name)
        [Required]  // 不能为空
        [DataType(DataType.Text)]   // @Html.EditorFor(s => s.Name)
        [RegularExpression("^[a-z]+$")] // 正则表达式
        [Compare("CId")]    // 用来和Cid属性的值进行判断比较
        [Remote("IsSame", "Home")]  // 用来 远程 Ajax请求 /Home/IsSame?Name = "xxx"的方法, 会自动根据方法返回值(bool)判断是否通过验证
        public string Name { get; set; }
        public string Gender { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime AddTime { get; set; }

        public Class Class { get; set; }
    }
}
