//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N29MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Msgs = new HashSet<Msg>();
            this.Msgs1 = new HashSet<Msg>();
        }
    
        public int uId { get; set; }
        public string uName { get; set; }
        public string uLoginName { get; set; }
        public string uPwd { get; set; }
        public System.DateTime uAddtime { get; set; }
        public bool uIsDel { get; set; }
    
        public virtual ICollection<Msg> Msgs { get; set; }
        public virtual ICollection<Msg> Msgs1 { get; set; }
    }
}
